[profile.default]
solc = "0.8.28"
ffi = true
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
via_ir = true
verbosity = 2
src = "src"
out = "out"
ast = true
build_info = true
extra_output = ["storageLayout"]
libs = ["lib"]

gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

eth_rpc_url = "${RPC_URL}"
etherscan_api_key = "${ETHERSCAN_API_KEY}"